---
title: "Zicht op LA"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: columns
    vertical_layout: fill
    theme: bootstrap
    
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Inleiding tot LA & Zopla {.storyboard}
=====================================

### Executive Summary Zopla Project 

#### Doelstelling

***<span style="color:blue">Welke toekomst ziet de UvA-organisatie voor Learning Analytics?</span>*** Deze vraag staat
centraal in dit project. Door het beantwoorden van de vraag wordt er richting gegeven aan
de invulling van het thema learning analytics binnen de portefeuille onderwijs van de
expertisegroep ICT voor Onderwijs UvA in 2017. In het advies ICT-projectenportfolio 2017
UvA wordt de potentie van learning analytics herkend en wordt geconstateerd dat er binnen
de UvA-organisatie onvoldoende draagvlak is voor een grootschalige implementatie van
learning analytics. De expertisegroep heeft in januari 2017 de richting vastgesteld voor
2017. In deze PID wordt de vastgestelde richting verder uitgewerkt.

####  Resultaten

In 2017 willen we de volgende resultaten bereiken (conform het memo zoals vastgesteld in
de expertisegroep ICT voor Onderwijs UvA in 2017):

* Zicht op learning analytics. In 2017 hebben de faculteiten een idee wat learning
analytics is, of faculteiten het willen inzetten en in welk tempo faculteiten dit zouden
willen doen. Op basis van dit inzicht wordt duidelijk wat er op instellingsniveau nodig is,
zodanig dat we eind 2017 goed onderbouwd uitspraken kunnen doen over welke weg
we de komende jaren inslaan met learning analytics. We verwoorden en verbeelden dit
inzicht communicatief en het bevat een roadmap/actieplan.

* Betrokkenheid bij learning analytics. Onderwijsdirecteuren, docenten en studenten
hebben inzicht in de thema???s learning analytics / student analytics en begrijpen welke
mogelijkheden learning analytics biedt en wat er nodig is om deze mogelijkheden
beschikbaar te stellen. Learning Analytics is voor velen binnen de UvA nog een diffuus
begrip. Het is niet moeilijk om te voorspellen dat er bij de studenten (via CSR) maar ook
bij docenten (via COR) veel vragen zullen rijzen over privacy en veiligheid van
gegevens, nut en noodzaak en evidentie.

* Opbouw van sociale infrastructuur. Op basis van deze visie vindt binnen de
faculteiten de start plaats van het opbouwen van een sociale infrastructuur voor
learning analytics.

* Inrichting Canvas. De mogelijkheden van Canvas zijn verkend en er is een voorstel
geformuleerd voor de inrichting van Canvas m.b.t. learning analytics.

* Synergie UvAData en learning analytics. Er is een antwoord geformuleerd op de
vraag: Wat is de synergie tussen UvAdata en learning analytics? Velen menen dat we
met UvAdata en UvAQ al voldoende data beschikbaar hebben om het studeergedrag te
kunnen analyseren. Er is tot een vorm van afstemming en samenwerking gekomen op
de raakvlakken tussen UvAdata en de ontwikkelingen rond learning analytics.

* Formuleren projecten voor 2018. Medio 2017 is er een grove roadmap opgesteld die
in het najaar van 2017 kan worden uitgewerkt naar projecten voor het portfolio voor het
jaar 2018.

#### Bereik

Dit project vraagt betrokkenheid van alle faculteiten (met name onderwijsdirecteuren en
medewerkers betrokken bij data-driven beleid- en besluitvorming en toepassingen
gerelateerd aan learning analytics) en ICTS. Dit project heeft niet als resultaat een dienst
die door faculteiten kan worden afgenomen.


### Inleiding tot het interview

Vanuit het UvA brede project Zicht op Learning Analytics (ZOPLA), een project ge-initieerd door de (voorzitter van de) expertisegroep Onderwijs Peter van Baalen (vice-provost, onderwijsinnovatie met ICT), wordt onderzocht en in kaart gebracht welke mogelijkheden Learning Analytics biedt voor de UvA en wat de verwachtingen en wensen vanuit het onderwijsmanagement zijn.
 
Voor de doelstelingen van het ZOPLA project is learning analytics gedefinieerd als het genereren van aanbevelingen aan studenten om hun onderwijs en gerelateerde uitkomsten te optimaliseren[i].
 
De UvA heeft inmiddels ervaring opgedaan met bottom up learning analytics experimenten, maar nog geen overkoepelende visie op de toekomst van Learning Analytics en de mogelijkheden die het biedt om evidentie te genereren voor de effectiviteit van onderwijspraktijken en interventies.
 
Wij willen graag met u in gesprek om mee te denken over de mogelijkheden en onmogelijkheden die Learning Analytics voor het UvA Onderwijs kan bieden. Vanuit het project is bijzondere interesse in de uitdagingen die onderwijs- en opleidingsdirecteuren zien bij het effectief en verantwoordelijk implementeren van Learning Analytics.

In het gesprek zullen de volgende thema's aan bod komen:

1. Wat is Learning Analytics precies en wat is het niet?
2. Rol van Learning Analytics bij activerend onderwijs en aansluiting bij de onderwijsvisie van de UvA
3. Interventies gericht op het verbeteren van persoonlijk studie succes door middel van data
4. Privacy kwesties en transparantie; wetgeving & ethiek; cre??ren van een veilige en betrouwbare omgeving
5. Evenwicht tussen investeringen (in mensen en benodigde financi??n) en impact



### LA 101 / Glossary

Learning Analytics (***LA***) has been defined as:

***<span style="color:blue">"the measurement, collection, analysis and reporting of data about learners and their contexts, for purposes of understanding and optimizing learning and the environments in which it occurs".</span>*** 

-- (*George Siemens*)


#### What does the definition imply

LA is focussed on using data to understand how students are learning, design interventions that help the students and supports teacher. Later we can measure the impact of the interventions. This is a cycle that optimizes learning environments and the educational process.

### Scoping of Learning analytics at UvA

There a number of types of LA actvities, including:

***Monitoring and analysis:*** In monitoring the objectives are to track student activities and generate reports in order to support decision-making by the teacher or the educational institution. Monitoring is also related to instructional design and refers to the evaluation of the learning process by the teacher with the purpose of continuously improving the learning environment. Examining how students use a learning system and analyzing student accomplishments can help teachers detect patterns and make decision on the future design of the learning activity.

***Prediction and intervention:*** In prediction, the goal is to develop a model that attempts to predict learner knowledge and future performance, based on his or her current activities and accomplishments. This predictive model can then be used to provide proactive intervention for students who may need additional assistance. The effective analysis and prediction of the learner performance can support the teacher or the educational institution in intervention by suggesting actions that should be taken to help learners improve their performance.

***Tutoring and Mentoring:*** Tutoring is mainly concerned with helping students with their learning (assignments), often very domain-specific and limited to the context of a course. A tutor, for example, supports learners in their orientation and introduction into new learning modules as well as instructions of specific subject matter areas within a course. In tutoring processes the control is with the tutor and the focus is rather on the teaching process. In contrast, mentoring goes beyond tutoring and focuses on supporting the learner throughout the whole process ??? ideally throughout the whole life, but in reality limited to the time that both mentor and learner are part of the same organization. As part of this support, mentors provide guidance in career planning, supervise goal achievement, help preparing new challenges, etc. In mentoring processes the control lies rather with the learners and the focus is on the learning process.

***Assessment and feedback:*** The objective is to support the (self-)assessment of improved efficiency and effectiveness of the learning process. Important is also to get intelligent feedback to both students and teachers/mentors. Intelligent feedback provides interesting information generated based on data about the user's interests and the learning context.

***Adaptation: Adaptation:*** is triggered by the teacher/tutoring system or the educational institution. The goal of LA here is to tell learners what to do next by adaptively organizing learning resources and instructional activities according to the needs of the individual learner.

***Personalization and recommendation:*** In personalization, LA is highly learner-centric, focusing on how to help learners decide on their own learning and continuously shape their PLEs to achieve their learning goals. A PLE-driven approach to learning suggests a shift in emphasis from a knowledge-push to a knowledge-pull learning model. In a learning model based on knowledge-push, the information flow is directed by the institution/teacher. In a learning model driven by knowledge-pull, the learner navigates toward knowledge. One concern with knowledge-pull approaches, though, is information overload. It thus becomes crucial to examine some mechanisms to help learners cope with the information overload problem. This is where recommender systems can play a crucial role to foster self-directed learning. The objective of LA in this case is to help learners decide what to do next by recommending to learners explicit knowledge nodes (i.e. learning resources) and tacit knowledge nodes (i.e. people), based on their preferences and activities of other learners with similar preferences.

***Reflection:*** Analytics can be a valuable tool to promote reflection. Students and teachers can benefit from data compared within the same course, across classes, or even across institutions to draw conclusions and (self-)reflect on the effectiveness of their learning or teaching practice. Learning by reflection (or reflective learning) offers the chance of learning by returning to and evaluating past work and personal experiences in order to improve future experiences and promote continuous learning.

### Huidig gebruik van educatieve gegevens @ UvA

#### Academic Analytics (UvAData) 

Is gericht op het monitoren van de organisatie en de organisatiedelen (de universiteit, faculteiten en opleidingen). Academic Analytics krijgt informatie uit de belangrijkste bronsysyemen (waaronder ***SISUvA, SAP, UVAQ***). Het geeft antwoord op generieke vragen als hoeveel studenten een bepaalde opleidingen volgen, hoe studenten hebben binnen periode x de opleiding afgerond, wat is de gemiddelde waardering van de studenten voor de opleiding, vak en/of voorzieningen. Academic analytics levert informatie voor het duurzaam besturen van de universiteit en de opleidingen en richt zich niet op de prestaties en gegevens van de individuele student of medewerker.

####Synergie UvAData en learning analytics.

Er is een antwoord geformuleerd op de vraag: Wat is de synergie tussen Institutional Research, UvAdata, en learning analytics? UvAData is meer gericht op het verstrekken van management informatie, en daarmee mogelijk minder geschikt (ook vanwege het aggregatieniveau van de data) om aanbevelingen te genereren richting individuele studenten. Sommigen menen dat we met UvAdata en UvAQ al voldoende data beschikbaar hebben om het studeergedrag te kunnen analyseren. Er is tot een vorm van afstemming en samenwerking gekomen op de raakvlakken tussen UvAdata en de ontwikkelingen rond learning analytics.

### Voorbeelden van onderwijssystemen aan de UvA

####	SISUvA

SIS is het studenteninformatiesysteem van de UvA. Hierin kunnen studenten:
* zich aanmelden voor vakken en tentamens
* hun studieresultaten, studievoortgang en studieadviezen bekijken
*	verzoekschriften indienen
*	een diploma aanvragen.
SIS stelt studenten de UvA in staat om te zien welke administratieve taken studenten uitvoeren.
(https://medewerker.uva.nl/bestuursstaf-gde/shared-content-secured/medewerkersites/uva-medewerkers/nl/az/sis/sis.html)


####	UvAData

De UvA heeft een online managementinformatiesysteem. Dit is UvAdata, het ???datawarehouse' van de UvA, een systeem dat continu in ontwikkeling is.

Bestuurders, managers en andere, daartoe geautoriseerde gebruikers kunnen hier online veel vergelijkende overzichten inzien plus detailgegevens over studenten en personeel, onderwijs, financi??n en huisvesting. Ook vinden zij hier gegevens over organisatiedelen en processen die relevant zijn voor het besturen en managen van de universiteit. Deze gegevens zijn zowel afkomstig uit de eigen concernadministraties als uit externe bronnen (VSNU, CBS).

(https://medewerker.uva.nl/content-secured/az/uvadata/uvadata.html)

####	UvAQ

UvA Q is de evaluatiemethode die door de UvA wordt gebruikt voor haar onderwijsevaluaties en is daarmee een belangrijk instrument om de kwaliteit van het onderwijs te bewaken en te verbeteren.

(https://medewerker.uva.nl/bestuursstaf-gde/shared-content-secured/medewerkersites/uva-medewerkers/nl/az/uva-q/uva-q.html)

####	DLO - Canvas

***Wat biedt Canvas docenten en studenten?***
Activerend, samenwerkend en gepersonaliseerd leren
Canvas biedt functionaliteiten die bijdragen aan verdiepend, activerend, samenwerkend en gepersonaliseerd leren. Studenten kunnen met verrijkte zelfstudie veel in Canvas  voorbereiden. Daardoor is er bij het contactonderwijs meer tijd voor dialoog, opdrachten, en verdieping.

***Goede koppeling leertools en op maat per faculteit in te richten***
Canvas is een open standaard systeem waardoor digitale leertools makkelijk ge??ntegreerd kunnen worden. Het kan per faculteit ???op maat??? ingericht worden naar de behoeften van de opleidingen. De kern biedt onderwijskundige basisdiensten voor alle faculteiten. De gemeenschappelijke schil bevat digitale leertools die alle faculteiten kunnen gebruiken. In de facultaire schil komen digitale leertools specifiek voor de opleidingen van die faculteit.

***Goede koppelingen met IDM, SIS, de Digitale Studiegids en het Rooster***
Canvas krijgt goede koppelingen met onderwijslogistieke systemen, zoals het SIS, de Digitale Studiegids en het Rooster. Hierdoor kunnen docenten en studenten effici??nter werken en studeren.

(http://naarcanvas.uva.nl/aan-de-slag/wat-is-canvas/wat-is-canvas.html)

#### Toetssystemen

De UvA biedt meerdere mogelijkheden om digitale toetsen/tentamens af te nemen bij studenten. Een digitaal tentamen is een tentamen dat met een toetsapplicatie op de computer wordt afgenomen. Het aanbieden van een digitale toets heeft diverse voordelen

* Gesloten vragen kunnen geautomatiseerd nagekeken worden, dit gaat dus sneller.
* Er is geen sprake van onleesbare handschriften.
*	Je kunt gebruikmaken van multimedia en andere functies die bij het schriftelijk afnemen van een toets niet mogelijk zijn.
Wat ruimer geformuleerd is digitale toetsing het inzetten van ICT-tools in het ontwikkelen, samenstellen, afnemen, beoordelen en analyseren van tentamens. Binnen de toetsapplicatie worden tentamenvragen ontworpen en worden tentamens samengesteld. De studenten ontvangen digitale feedback op hun prestaties. De resultaten van studenten zijn in de toetsapplicatie te analyseren, zoals kwaliteit van de items en de cesuurbepaling.
Digitaal toetsen omvat de volgende onderdelen:
*	Een digitale itembank (collectie open en/of gesloten vragen)
*	Een afnametool voor het online afnemen van tentamens
*	Digitaal gegenereerde feedback
*	Digitaal gegenereerde analyse
(https://medewerker.uva.nl/bestuursstaf-gde/shared-content-secured/medewerkersites/uva-medewerkers/nl/az/digitaal-toetsen/digitaal-toetsen.html)

### Scenarios

If you look above in the menu bar you will notice the ***<span style="color:blue">'LA in 2025'</span>*** option. Here are listed a number of scenarios that are sterotypically plausible for the year 2025.

You will find the source here:

http://www.laceproject.eu/the-lace-visions-of-the-future-of-learning-analytics/

### Resources

#### Interessante artikelen en websites

Overzicht van artikelen die een overzicht en een beeld geven van de ontwikkelingen in het hoger onderwijs die aansluiten bij de ambities van Zopla voor het inzetten learning analytics als UvA breed instrument.

* ***Architecting for Learning Analytic,*** innovation for Sustainable Impact (Educause Review, March/April 2018); Simon J. Buckingham Shum and Timothy A. McKay, https://er.educause.edu/articles/2018/3/architecting-for-learning-analytics-innovating-for-sustainable-impact

* ***Penetrating the Fog, Analytics in Learning and Education,*** Educause review (sept-okt 2011) Phil Long and George Siemens; https://www.educause.edu/ir/library/pdf/ERM1151.pdf ;  Artikel van enige tijd terug dat een basiselementen beschrijft waar de Learning Analytics Community in jaren daarna invulling aan heeft gegeven. Artikel kan gezien worden als een eerste aanzet om de ontwikkelingen rond Learning Analytics in een breder perspectief te plaatsen en toegankelijk te maken voor een breder publiek in het Hoger Onderwijs

* ***LACE, European Learning Analytics community***  http://www.laceproject.eu/ 

* ***EU Sheila project,*** To assist European universities to become more mature users and custodians of digital data about their students as they learn online, the SHEILA project will build a policy development framework that promotes formative assessment and personalized learning, by taking advantage of direct engagement of stakeholders in the development process. http://sheilaproject.eu/

* ***How Personalized Learning Unlocks Student Success,*** Educause review (maart-april 2016) Nazeema Alli, Rahim Rajan, and Greg Ratliff; https://er.educause.edu/articles/2016/3/how-personalized-learning-unlocks-student-success ; De belofte van learning analytics is vooral gekoppeld aan Student Success. Dit artikel beschrijft een aantal ontwikkelingen uitdagingen die bij kunnen dragen aan student succes

* ***Learning Analytics in Higher Education,*** A review of UK and international practice (April 2016) https://analytics.jiscinvolve.org/wp/2016/04/19/learning-analytics-in-higher-education-a-review-of-uk-and-international-practice/


* ***SURF Learning Analytics website & landelijke community,*** https://www.surf.nl/themas/onderwijsinnovatie-met-ict/learning-analytics

* ***Online Report by Jisc, Code of practice for learning analytics,*** Setting out the responsibilities of educational institutions to ensure that learning analytics is carried out responsibly, appropriately and effectively; https://www.jisc.ac.uk/guides/code-of-practice-for-learning-analytics

#### MAIN Conferences on LA in 2018 / 2019

* SURF onderwisjdagen
https://www.surfonderwijsdagen.nl/
* LSAC 2018
http://lsac2018.org/
* LAK
https://lak19.solaresearch.org/
* Hackathons
    - LSAC 2018
http://lsac2018.org/#hackathon
    - LAK19 (to be declared)
https://lakhackathon.files.wordpress.com/2018/02/lakhackathon2018_paper_2.pdf



LA in 2025   { .storyboard}
=====================================

### ***Visie 1:*** In 2025, controleren onderwijsruimtes de fysieke omgeving om leren en onderwijs te ondersteunen

***Visie 1: In 2025, controleren onderwijsruimtes de fysieke omgeving om leren en onderwijs te ondersteunen***

In 2015 werd learning analytics met name toegepast om het online leren te ondersteunen. In 2025 kan het gebruikt worden om de meeste onderwijs- en leeractiviteiten te ondersteunen, ongeacht de locatie. Meubels, pennen, notitieblokken – bijna alle middelen die gebruikt worden in het leerproces – kunnen uitgerust worden met sensoren. Deze sensoren kunnnen allerlei informatie verzamelen, inclusief helling, kracht en locatie. Video camera’s gebruiken gezichtsherkenning en volgen individuele studenten terwijl ze aan het leren zijn. Deze camera’s vergaren gegevens over bewegingen, registreren exact hoe studenten werken met objecten en hoe ze deze manipuleren. Al deze informatie wordt gebruikt om de voortgang van studenten te volgen en om daar waar nodig bij te sturen. Studenten worden zo ondersteund in het leren van een een breed scala aan fysieke vaardigheden. Docenten worden op het niveau van de individuele student op de hoogte gebracht van signalen van verveling, verwarring en afwijking van de taak. Docenten en managers zijn in staat om sociale interacties te observeren, en om in te grijpen teneinde socialisatie en cooperatief gedrag te bevorderen. 

### ***Visie 2:*** In 2025, persoonlijke data sporen ondersteunen het leerproces

***Visie 2: In 2025, persoonlijke data sporen ondersteunen het leerproces***

In 2015, begonnen mensen met het dagelijks dragen van apparatuur zoals hartslagmeters en fitness trackers. In 2025, kunnen geavanceerde sensoren persoonlijke informatie verzamelen met betrekking tot lichaamshouding, aandacht, rust, stress, bloedsuikerspiegel, en metabolisme. Mensen verzamelen dergelijke informatie over hun activiteiten en kiezen zelf of ze deze delen met programma’s die op basis van deze data aanbevelingen genereren over hoe zich in bepaalde omstandigheden te gedragen zodat het leerproces wordt geoptimaliseerd. Studenten kunnen die  statistieken en data downloaden die in een bepaald domein geassocieerd zijn met studiesuccess. Het idee is dat mensen door hun  persoonlijke data op deze ‘idealen’ af te stemmen zich kunnen bekwamen in diverse vaardigheden, zoals zwemmen, autorijden, chirurgie en het slagen voor tentamens. Academische talenten verkopen programmas die gebaseerd zijn op deze data om het leerproces voor verschillende leeftijden en cursussen te optimaliseren. Zakelijke goeroes vermarkten soortgelijke programma’s voor onderwerpen als presentatievaardigheden en burnoutpreventie. Sommige studenten kiezen ervoor hun zelfontworpen data analyse programmas te delen, welke vaak aanbevelingen doen met betrekking tot de consumptie van hoog energetisch voedsel en stimulerende middelen. Het overgrote gedeelte van middelbare scholieren en studenten in het hoger onderwijs volgen zelfhulp progammas en disccussieren de voor- en nadelen hiervan op sociale media.

### ***Visie 3:*** In 2025 worden analytics zelden toegepast in onderwijs

***Visie 3: In 2025 worden analytics zelden toegepast in onderwijs***

In 2015 hoopten velen dat analytics gebruikt zouden kunnen worden om het onderwijs, het leerproces en de omgeving waarin deze plaatsvinden te verbeteren. In 2025 is het echter duidelijk dat er veel problemen zijn. Cursessen die geautomatiseerd zijn met analytics worden gepercieerd als inferieur en studenten zijn erachter gekomen dat ze de analytics kunnen misleiden. Er hebben zich grote lekken voorgedaan van gevoelige persoonlijke informatie, en het is duidelijk dat zelfs daar waar dit niet is gebeurd, bedrijven misbruik hebben gemaakt van gegevens die door hun analytics zijn gegenereerd. Veel overheden hebben bepaald dat individuen de enige rechtmatige eigenaren zijn van de data die ze genereren. Al het gebruik van data voor onderwijsdoeleinden moet nu goedgekeurd worden door niet alleen de student, maar ook nieuwe inspectoraten die met deze taak zijn belast. In de praktijk betekent dit dat het gebruik van analytics is beperkt tot summatieve toetsen die worden uitgevoerd door de overheid. Met betrekking tot onderwijsbeleid is een consensus ontstaan: Het schuwen van learning analytics is niet alleen wenselijk vanuit ethisch oogpunt, het draagt ook bij aan de effectiviteit van het onderwijs.

### ***Visie 4:*** In 2025 hebben individuen volledige zeggenschap over hun eigen data

***Visie 4: In 2025 hebben individuen volledige zeggenschap over hun eigen data***

In 2015 was er veel onduidelijkheid omtrent het eigenaarschap van onderwijsdata en werden deze vaak gebruikt zonder dat de student daarvan op de hoogte was. In 2025 zijn de meeste mensen doordrongen van het belang en de waarde van hun data. Studenten hebben volledige controle over het soort en de hoeveelheid van persoonlijke data die ze delen, en met wie ze deze delen. Dit behelst informatie over voortgang, aanwezigheid, en tentamenresultaten, als ook data die worden verzameld door middel van cameras en sensoren. Studenten kunnen kiezen om de tijdsperiode waarbinnen data kunnen worden gebruikt te beperken of ze kunnen de toegang voor specifieke organisaties of individuen ontzeggen. De tools die deze keuzen facciliteren zijn duidelijk omschreven en gebruiksvriendelijk. Daar waar het data over minderjarigen betreft, worden data besluiten gemaakt in consultatie met ouders of anderen die over de voogdij beschikken. Als zij ervoor kiezen deze tools niet te raadplegen worden data niet gedeeld en worden zijn er ook geen baten. De meeste onderwijsinstellingen onderkennen deze stand van zaken als een potentieel probleem en voeren campagne om het bewustzijn te vergroten over enerzijds de risicos van het onbezonnen delen van data, en anderzijds de voordelen voor studenten van het geinformeerd delen van een selectie van onderwijsdata.


### ***Visie 5:*** In 2025, zijn open systemen voor learning analytics breed geimplementeerd

***Visie 5: In 2025, zijn open systemen voor learning analytics breed geimplementeerd***

In 2015, produceerden bedrijven een breed scala aan learning analytics tools, door gebruik te maken van verschillende benaderingen en standaarden. De algoritmes en modellen die bedrijven gebruiken werden vaak beschermd als intellectueel eigendom. In 2025, zijn ‘open learning analytics’ ingevoerd door de Open Learning Analytics foundation, waardoor samenwerkingen worden gefaciliteerd. Ondewijsinstellingen zien learning analytics als een centraal element van hun IT portfolio. Zij willen controle over de tools, hoe ze werken en waarvoor ze worden gebruikt. Alhoewel deze worden geleverd door verschillende leveranciers, gebruiken de tools die zij selecteren, open algoritmes en worden data gedeeld onder een afgeproken set aan standaarden die transparantie en onafhankelijke validatie mogelijk maken. Er word gebruik gemaakt van een en aantal goed geteste, toegankelijke en gestandaardiseerde visualisatie methoden, zodat studenten en docenten zelfverzekerd een scala aan tools kunnen gebruiken.Onderwijsinstellingen kunnen efficient samenwerken met verschillende providers om learning analytics systemen zo te ontwikkelen, dat deze aansluiten bij hun onderwijsvisie.

### ***Visie 6:*** in 2025 zijn learning analytics systemen essentiele tools in onderwijsmanagement

***Visie 6: in 2025 zijn learning analytics systemen essentiele tools in onderwijsmanagement***

In 2025 begonnen bedrijven systemen te ontwikkelen om verschillende hulpbronnen aan te bevelen en uitkomsten te voorspellen. In 2025 zijn deze systeem uitontwikkeld. Een breed scala aan data over leergedrag wordt gebruikt om hoogwaardige en real-time voorspellingen te doen over de kans op success. Student, docenten, managers en beleidsmakers hebben allemaal toegang tot ‘live’ en accurate informatie over hoe goed een student zal presteren. Studenten en docentten plannen hun werk op basis van betrouwbare tools die gedetailleerde en gepersonaliseerde  aanbevelingen doen over hoe de beste leeruitkomsten kunnen worden bereikt. Een groeiende bedrijfstak levert diensten aan instellingen en individuen, om hen te adviseren over hoe te handelen in het licht van de de voorspellingen die aan de hand van learning analytics worden gegenereerd. Accurate voorspellingen stellen managers en beleidsmakers in staat om meer of minder onderwijs te verschaffen voordat de student het duidelijk is of de student slaagt of niet: men hoeft niet te wachten om te zien dat een cursus succesvol is of niet, en er wordt snel ingegrepen.


### ***Visie 7:*** In 2025 zijn de meeste onderwijstaken overgenomen door computers

***Visie 7: In 2025 zijn de meeste onderwijstaken overgenomen door computers***

In 2015 begonnen mensen datasets te vergaren waarmee het leergedrag van student in kaart kon worden gebracht. In 2025 worden deze op grote schaal gebruikt in het onderwijs, en dit heeft tot enorme datasets met informatie over honderdduizenden studenten geleid.  Door de voortgang over zo’n aantal studenten in detail te analyseren is het mogelijk geworden betrouwbare ‘evidence-based’ aanbevelingen te doen over de meest succesvolle leertrajecen, en het onderwijsmateriaal en de benanderingen die voor elk individu het meest effectief zijn op elk punt in hun studie. Deze aanbevelingen zijn beter geinformeerd en meer betrouwbaar dan de aanbevelingen die kunnen worden gedaan door zelfs de best getrainde mensen. Studenten spenderen het gros van hun tijd aan het werken met door analytics gedreven systemen. De rol van de docenten is veel minder belangrijk geworden. De evidentie due de systemen generen wordt gebruikt om onderwijsbeleid te formuleren.


### ***Vision 8***: In 2025, ondersteunen analytics zelf-gedirigeerd autonoom leren.

***Vision 8: In 2025, ondersteunen analytics zelf-gedirigeerd autonoom leren.

In 2015, volgden studenten in onderwijsinstellingen en het bedrijfsleven curricula die door anderen waren samengesteld. In 2025 creeren zij groepen die samen de eigen leerdoelen bepalen en hoe deze te behalen. Een ‘Learning Trajectory’ systeem gebruikt analytics om informatie uitwisseling te ondersteunen en groepswerk te facciliteren, en studenten ontvangen ondersteuning van mentoren in tegenstelling tot docenten. Activiteiten die bijdragen aan het behalen van bepaalde leerdoelen worden nauwgezet gevolgd, en analytics geven de individuele student feedback over zijn of haar leerproces. Hieronder vallen suggesties, medestudenten of experts om te benaderen, inhoudelijke stof, en manieren om nieuwe vaardigheden te oefenen en te tonen. Formatieve toesten worden gebruikt om toekomstige vooruitgang te ondersteune, waarbij individuele verschillen, ervaring, en context in ogenschouw worden genomen, en tentamens die alleen inzicht gaven in wat er is geleerd zijn komen te vervallen. Teksten en andere onderwijsmaterialen worden aangepast op de culturele achtergrond van studenten, die wordt afgeleid uit hun interacties. Het resultaat hiervan is dat studenten persoolijk geengageerd zijn met hun onderwerpen, en zeer gemotiveerd zijn als gevolg van het autonome leren. De competenties die zij ontwikkelen zijn waardevol in de maatschappij, waar het verzamelen en analyseren van data inmiddels de norm is geworden. Er is ook een convergentie tussen de leeractiviteiten van het onderwijssysteem en de methoden die door werknemers worden gebruikt om hun kennis en vaardigheden verder te ontwikkelen. 

Wie zijn we?
=====================================

#### Core Team

1. ***Stefan T Mol*** \
   Primary investigator\
   
   
2. ***Frank Benneker***\
   UvA Information Manager Education
   
   
3. ***Sjoukje Keemans***\
   Consultant\
  

4. ***Alan M Berg*** \
   Data Scientist, PhD Candidate Learning Analytics

#### Contact

* Primary ***contact***: \
              Stefan T Mol\
              \

* For LA ***technological reviews***: \
              Alan M Berg\
              a.m.berg AT uva.nl\
